/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux paldier-VirtualBox 4.2.0-42-generic #49~14.04.1-Ubuntu SMP Wed Jun 29 20:22:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux"
#define BUILD_ENV_DATE "2018年 01月 22日 星期一 23:27:59 CST"
#define BUILD_ENV_SRCDIR "/home/paldier/asuswrt/release/src/router/samba-3.0.33/source"
#define BUILD_ENV_BUILDDIR "/home/paldier/asuswrt/release/src/router/samba-3.0.33/source"
#define BUILD_ENV_USER "paldier"
#define BUILD_ENV_HOST "paldier-VirtualBox"
#define BUILD_ENV_COMPILER "mips-openwrt-linux-uclibc-gcc"
#endif /* _BUILD_ENV_H */
