/*
 * Automatically generated C config: don't edit
 */
#undef RTCONFIG_REALTEK
#undef RTCONFIG_RTL819X
#undef RTCONFIG_RTL8197F
#undef RTCONFIG_RTK_NAND
#define RTCONFIG_OPTIMIZE_SHARED_LIBS 1
#define RTCONFIG_L2TP 1
#define RTCONFIG_PPTP 1
#define RTCONFIG_EAPOL 1
#undef RTCONFIG_PPTPD
#define RTCONFIG_ACCEL_PPTPD 1
#undef RTCONFIG_SNMPD
#define RTCONFIG_HTTPS 1
#undef RTCONFIG_BCMARM
#undef RTCONFIG_BCM7
#undef RTCONFIG_BCM_794
#undef RTCONFIG_BCM_7114
#undef RTCONFIG_HND_ROUTER
#undef RTCONFIG_BCM9
#undef RTCONFIG_BUILDBCM7
#undef RTCONFIG_ROMCFE
#undef RTCONFIG_ROMATECCODEFIX
#undef RTCONFIG_NV128
#define RTCONFIG_NVRAM_SIZE 0x10000
#undef RTCONFIG_DHDAP
#undef RTCONFIG_WLEXE
#undef RTCONFIG_DPSTA
#undef RTCONFIG_GMAC3
#undef RTCONFIG_BCMSMP
#undef RTCONFIG_BCMFA
#undef RTCONFIG_RGMII_BCM_FA
#undef RTCONFIG_5301X
#undef RTCONFIG_4352_5G
#define RTCONFIG_SSH 1
#undef RTCONFIG_CIFS
#undef RTCONFIG_BRCM_NAND_JFFS2
#undef RTCONFIG_JFFS2
#undef RTCONFIG_DISKTEST
#undef RTCONFIG_ZEBRA
#define RTCONFIG_QUAGGA 1
#define RTCONFIG_DDNS 1
#undef RTCONFIG_L7
#define RTCONFIG_LZO 1
#define RTCONFIG_OPENVPN 1
#undef RTCONFIG_IPSEC
#define RTCONFIG_IPV6 1
#define RTCONFIG_EBTABLES 1
#define RTCONFIG_EMF 1
#undef RTCONFIG_BCMBSD
#undef RTCONFIG_BCMSSD
#undef RTCONFIG_BCMDCS
#undef RTCONFIG_TOAD
#undef RTCONFIG_BCM_MEVENT
#undef RTCONFIG_BCMEVENTD
#undef RTCONFIG_BCM_APPEVENTD
#undef RTCONFIG_HSPOT
#undef RTCONFIG_FANCTRL
#undef RTCONFIG_BCMWL6
#undef RTCONFIG_WIRELESSWAN
#define RTCONFIG_WIRELESSREPEATER 1
#undef RTCONFIG_REPEATER
#undef RTCONFIG_DISABLE_REPEATER_UI
#define RTCONFIG_PROXYSTA 1
#undef RTCONFIG_DISABLE_PROXYSTA_UI
#undef RTCONFIG_PSR_GUEST
#undef RTCONFIG_CONCURRENTREPEATER
#undef RTCONFIG_VHT80_80
#undef RTCONFIG_VHT160
#undef RTCONFIG_IXIAEP
#undef RTCONFIG_IPERF
#undef RTCONFIG_TCPDUMP
#undef RTCONFIG_DUMP4000
#undef RTCONFIG_TRACEROUTE
#undef RTCONFIG_NETOOL
#define RTCONFIG_PARENTALCTRL 1
#undef RTCONFIG_YANDEXDNS
#undef RTCONFIG_DSL
#undef RTCONFIG_DSL_ANNEX_B
#undef RTCONFIG_DSL_TCLINUX
#undef RTCONFIG_VDSL
#undef RTCONFIG_SYSSTATE
#undef RTCONFIG_DUALWAN
#undef RTCONFIG_HW_DUALWAN
#undef RTCONFIG_USER_LOW_RSSI
#define RTCONFIG_NEW_USER_LOW_RSSI 1
#define RTCONFIG_PUSH_EMAIL 1
#define RTCONFIG_DBLOG 1
#undef RTCONFIG_NO_USBPORT
#define RTCONFIG_USB 1
#undef RTCONFIG_USBRESET
#undef RTCONFIG_WIFIPWR
#undef RTCONFIG_XHCIMODE
#define RTCONFIG_MEDIA_SERVER 1
#undef RTCONFIG_MEDIASERVER_LIMIT
#undef RTCONFIG_NO_DAAPD
#define RTCONFIG_CLOUDSYNC 1
#define RTCONFIG_SWEBDAVCLIENT 1
#define RTCONFIG_DROPBOXCLIENT 1
#define RTCONFIG_GOOGLECLIENT 1
#define RTCONFIG_FTPCLIENT 1
#define RTCONFIG_SAMBACLIENT 1
#define RTCONFIG_USBCLIENT 1
#undef RTCONFIG_FLICKRCLIENT
#define RTCONFIG_FTP 1
#undef RTCONFIG_FTP_SSL
#define RTCONFIG_WEBDAV 1
#define RTCONFIG_SAMBASRV 1
#define RTCONFIG_SAMBA3 1
#undef RTCONFIG_SAMBA36X
#define RTCONFIG_USB_EXTRAS 1
#define RTCONFIG_E2FSPROGS 1
#define RTCONFIG_EXT4FS 1
#define RTCONFIG_TFAT 1
#undef RTCONFIG_OPENPLUS_TFAT
#define RTCONFIG_NTFS 1
#undef RTCONFIG_PARAGON_NTFS
#define RTCONFIG_TUXERA_NTFS 1
#undef RTCONFIG_OPEN_NTFS3G
#define RTCONFIG_HFS 1
#undef RTCONFIG_PARAGON_HFS
#define RTCONFIG_TUXERA_HFS 1
#undef RTCONFIG_KERNEL_HFSPLUS
#define RTCONFIG_DISK_MONITOR 1
#define RTCONFIG_USB_PRINTER 1
#define RTCONFIG_USB_MODEM 1
#undef RTCONFIG_USB_LESSMODEM
#define RTCONFIG_USB_MODEM_PIN 1
#undef RTCONFIG_USB_SMS_MODEM
#undef RTCONFIG_USB_BECEEM
#undef RTCONFIG_INTERNAL_GOBI
#undef RTCONFIG_DYN_MODEM
#undef RTCONFIG_BRCM_USBAP
#undef RTCONFIG_APP_PREINSTALLED
#define RTCONFIG_APP_NETINSTALLED 1
#undef RTCONFIG_RALINK
#define RTCONFIG_NEWSSID_REV2 1
#undef RTCONFIG_QCA
#undef RTCONFIG_QCA_BIGRATE_WIFI
#undef RTCONFIG_NEW_APP_ARM
#undef RTCONFIG_QCA_ARM
#undef RTCONFIG_QCA953X
#undef RTCONFIG_QCA956X
#undef RTCONFIG_SOC_IPQ40XX
#undef RTCONFIG_FITFDT
#undef RTCONFIG_QCA_VAP_LOCALMAC
#undef RTCONFIG_QCA_PLC_UTILS
#undef RTCONFIG_AR7420
#undef RTCONFIG_QCA7500
#define RTCONFIG_AIR_TIME_FAIRNESS 1
#define RTCONFIG_POWER_SAVE 1
#undef RTCONFIG_QCA8033
#undef RTCONFIG_ART2_BUILDIN
#undef RTCONFIG_DEFAULT_AP_MODE
#undef RTCONFIG_DEFAULT_REPEATER_MODE
#define RTCONFIG_ODMPID 1
#undef RTCONFIG_32BYTES_ODMPID
#undef RTCONFIG_NONASUS
#define RTCONFIG_TIMEMACHINE 1
#define RTCONFIG_MDNS 1
#define RTCONFIG_FINDASUS 1
#undef RTCONFIG_REDIRECT_DNAME
#undef RTCONFIG_MTK_TW_AUTO_BAND4
#undef RTCONFIG_QCA_TW_AUTO_BAND4
#undef RTCONFIG_LED_ALL
#undef RTCONFIG_COMA
#undef CONFIG_LIBBCM
#undef CONFIG_LIBUPNP
#define RTCONFIG_WPS 1
#undef RTCONFIG_NFC
#define RTCONFIG_WPS_ENROLLEE 1
#undef RTCONFIG_WIFI_CLONE
#define RTCONFIG_SHP 1
#undef RTCONFIG_SFP
#undef RTCONFIG_STRACE
#undef RTCONFIG_4M_SFP
#undef RTCONFIG_8M_SFP
#undef RTCONFIG_16M_RAM_SFP
#define RTCONFIG_GROCTRL 1
#define RTCONFIG_LANWAN_LED 1
#undef RTCONFIG_WLAN_LED
#undef RTCONFIG_FAKE_ETLAN_LED
#undef RTCONFIG_EXT_LED_WPS
#undef RTCONFIG_SWMODE_SWITCH
#undef RTCONFIG_WL_AUTO_CHANNEL
#undef RTCONFIG_SMALL_FW_UPDATE
#undef RTCONFIG_WIRELESS_SWITCH
#undef RTCONFIG_WIFI_TOG_BTN
#undef RTCONFIG_WPS_RST_BTN
#undef RTCONFIG_WPS_ALLLED_BTN
#undef RTCONFIG_LOGO_LED
#undef RTCONFIG_LED_BTN
#undef RTCONFIG_USBEJECT
#define RTCONFIG_AUTODICT 1
#undef RTCONFIG_AUTOLIVEUPDATE_ZIP
#undef RTCONFIG_ISP_METER
#define RTCONFIG_NVRAM_64K 1
#undef RTCONFIG_NVRAM_FILE
#define RTCONFIG_USB_XHCI 1
#undef RTCONFIG_WLMODULE_RT3090_AP
#undef RTCONFIG_WLMODULE_RT3352_INIC_MII
#undef RTCONFIG_WLMODULE_MT7610_AP
#undef RTCONFIG_WLMODULE_RLT_WIFI
#undef RTCONFIG_WLMODULE_MT7603E_AP
#undef RTCONFIG_WLMODULE_MT7628_AP
#undef RTCONFIG_WLMODULE_MT7615E_AP
#define RTCONFIG_PSISTLOG 1
#undef RTCONFIG_DUAL_TRX
#define RTCONFIG_UBI 1
#define RTCONFIG_UBIFS 1
#undef RTCONFIG_YAFFS
#undef RTCONFIG_SAVEJFFS
#define RTCONFIG_OPTIMIZE_XBOX 1
#undef RTCONFIG_NEW_REGULATION_DOMAIN
#undef RTCONFIG_DYN_DICT_NAME
#undef RTCONFIG_LAN4WAN_LED
#undef RTCONFIG_DMALLOC
#undef RTCONFIG_JFFS2ND_BACKUP
#undef RTCONFIG_TEMPROOTFS
#define RTCONFIG_ATEUSB3_FORCE 1
#undef RTCONFIG_WPSMULTIBAND
#undef RTCONFIG_RALINK_DFS
#undef RTCONFIG_ENGINEERING_MODE
#define RTCONFIG_VPNC 1
#undef RTCONFIG_KYIVSTAR
#undef RTCONFIG_NO_WANPORT
#undef RTCONFIG_WANPORT2
#undef RTCONFIG_MULTIWAN_CFG
#undef RTCONFIG_TFTP_SERVER
#undef RTCONFIG_ETRON_XHCI
#undef RTCONFIG_ETRON_XHCI_USB3_LED
#undef RTCONFIG_WPS_LED
#undef RTCONFIG_MMC_LED
#undef RTCONFIG_RESET_SWITCH
#define RTCONFIG_WANRED_LED 1
#define RTCONFIG_PWRRED_LED 1
#define RTCONFIG_FAILOVER_LED 1
#undef RTCONFIG_SATA_LED
#undef RTCONFIG_BLINK_LED
#undef RTCONFIG_LEDS_CLASS
#define RTCONFIG_EJUSB_BTN 1
#undef RTCONFIG_M2_SSD
#undef RTCONFIG_WIGIG
#undef RTCONFIG_CFE_NVRAM_CHK
#undef RTCONFIG_DEBUG
#undef RTCONFIG_LLDP
#define RTCONFIG_HAS_5G 1
#undef RTCONFIG_HAS_5G_2
#undef RTCONFIG_TFTP
#undef RTCONFIG_QTN
#undef RTCONFIG_ALPINE
#undef RTCONFIG_QSR10G
#define RTCONFIG_LANTIQ 1
#undef RTCONFIG_N18UTXBF
#define RTCONFIG_BWDPI 1
#undef RTCONFIG_TRAFFIC_LIMITER
#undef RTCONFIG_SPEEDTEST
#undef RTCONFIG_BONDING
#undef RTCONFIG_UIDEBUG
#undef RTCONFIG_ROG
#undef RTCONFIG_GEOIP
#undef RTCONFIG_TRANSMISSION
#define RTCONFIG_TCODE 1
#undef RTCONFIG_WIFILOGO
#define RTCONFIG_JFFS2USERICON 1
#undef RTCONFIG_EXT_RTL8365MB
#undef RTCONFIG_EXT_RTL8370MB
#undef RTCONFIG_EXT_BCM53134
#undef RTCONFIG_TOR
#undef RTCONFIG_TR069
#undef RTCONFIG_TR181
#define RTCONFIG_STAINFO 1
#undef RTCONFIG_CLOUDCHECK
#define RTCONFIG_GETREALIP 1
#undef CONFIG_ASUS_APCLI_WPS
#define RTCONFIG_TUNNEL 1
#define RTCONFIG_AICLOUD_TUNNEL 1
#define RTCONFIG_AIHOME_TUNNEL 1
#undef RTCONFIG_CFEZ
#undef RTCONFIG_RESTRICT_GUI
#undef RTCONFIG_LACP
#undef RTCONFIG_KEY_GUARD
#undef RTCONFIG_RECVFILE
#undef RTCONFIG_WTFAST
#define RTCONFIG_ALEXA 1
#define RTCONFIG_IFTTT 1
#define RTCONFIG_UTF8_SSID 1
#undef RTCONFIG_ERP_TEST
#define RTCONFIG_REBOOT_SCHEDULE 1
#undef RTCONFIG_CAPTIVE_PORTAL
#undef RTCONFIG_CP_FREEWIFI
#undef RTCONFIG_CP_ADVANCED
#undef RTCONFIG_UPNPC
#define RTCONFIG_MULTICAST_IPTV 1
#undef RTCONFIG_BONJOUR
#undef RTCONFIG_FORCE_AUTO_UPGRADE
#undef RTCONFIG_CHILLISPOT
#undef RTCONFIG_COOVACHILLI
#undef RTCONFIG_FREERADIUS
#undef RTCONFIG_TUXERA_SMBD
#undef RTCONFIG_BCMASPMD
#undef RTCONFIG_FBT
#undef RTCONFIG_WLCLMLOAD
#undef RTCONFIG_MUMIMO
#define RTCONFIG_NOTIFICATION_CENTER 1
#define RTCONFIG_PROTECTION_SERVER 1
#undef RTCONFIG_WLCEVENTD
#define RTCONFIG_HAPDEVENT 1
#define RTCONFIG_6RELAYD 1
#undef RTCONFIG_PORT_BASED_VLAN
#undef RTCONFIG_TAGGED_BASED_VLAN
#undef RTCONFIG_DISABLE_NETWORKMAP
#undef RTCONFIG_WAN_AT_P4
#undef RTCONFIG_MTK_REP
#undef RTCONFIG_ATED122
#undef RTCONFIG_NOIPTV
#undef RTCONFIG_MTK_NAND
#undef RTCONFIG_RALINK_EDCCA
#define RTCONFIG_AUTOCOVER_SIP 1
#define RTCONFIG_DEFLAN50 1
#undef RTCONFIG_ALL_DEF_LAN50
#undef RTCONFIG_VPN_FUSION
#undef RTCONFIG_LBR_AGGR
#undef RTCONFIG_FLATLAS
#undef RTCONFIG_WBD
#undef RTCONFIG_QAM256_2G
#undef RTCONFIG_MUMIMO_2G
#undef RTCONFIG_MUMIMO_5G
#undef RTCONFIG_CONNTRACK
#undef RTCONFIG_PERMISSION_MANAGEMENT
#define RTCONFIG_LETSENCRYPT 1
#undef RTCONFIG_DETWAN
#define RTCONFIG_CFGSYNC 1
#undef RTCONFIG_LP5523
#undef RTCONFIG_SINGLE_SSID
#undef RTCONFIG_SSID_AMAPS
#undef RTCONFIG_HIDDEN_BACKHAUL
#undef RTCONFIG_ETHBACKHAUL
#undef RTCONFIG_AUTHSUPP
#undef RTCONFIG_FBWIFI
#define RTCONFIG_ADV_RAST 1
#undef RTCONFIG_WLCSCAN_RSSI
#define RTCONFIG_BT_CONN 1
#undef RTCONFIG_RGBLED
#define RTCONFIG_I2CTOOLS 1
#undef RTCONFIG_MTK_8021X3000
#undef RTCONFIG_INTEL
#undef RTCONFIG_DBG_BLUECAVE_OBD
#define RTCONFIG_AMAS 1
#undef RTCONFIG_LYRA_5G_SWAP
#undef RTCONFIG_NO_SELECT_CHANNEL
#undef RTCONFIG_USB_SWAP
#define RTCONFIG_SW_DEVLED 1
#undef RTCONFIG_LYRA_HIDE
#undef RTCONFIG_PORT2_DEVICE
#undef RTCONFIG_NVRAM_ENCRYPT
#undef RTCONFIG_WIFI_PROXY
#define RTCONFIG_HD_SPINDOWN 1
#define RTCONFIG_MASTER_DET 1
#undef RTCONFIG_ADTBW
#undef RTCONFIG_TXBF_BAND3ONLY
#define RTCONFIG_SW_HW_AUTH 1
#define RTCONFIG_LIBASUSLOG 1
#define RTCONFIG_ETHOBD 1
#define RTCONFIG_DWB 1
#define RTCONFIG_NO_TRY_DWB_PROFILE 1
#undef RTCONFIG_CONNDIAG
#undef RTCONFIG_REPEATER_STAALLBAND
#undef RTCONFIG_QCA_LBD
#define RTCONFIG_OPENSSL10 1
#undef RTCONFIG_OPENSSL11
#define RTCONFIG_SOFTCENTER 1
#define RTCONFIG_SMARTDNS 1
#define RTCONFIG_FRS_LIVE_UPDATE 1
#undef RTCONFIG_UUPLUGIN
#define RTCONFIG_FRS_FEEDBACK 1
