#!/bin/sh

######################################################################
#
# Function  : init script, telnetd_startup
#
# Creater   : xiangda.zhang@feixun.com.cn, 2016-05-04
#
# Copyright : Shanghai Phicomm
#
######################################################################

start() {
#  /usr/sbin/gpio.sh yellow 0
#  sleep 40
  /usr/sbin/gpio.sh blue 0
}

stop() {
  echo 1 > /sys/class/gpio/gpio34/value
  echo 0 > /sys/class/gpio/gpio35/value
  echo 1 > /sys/class/gpio/gpio36/value
}
start
