#!/bin/sh

######################################################################
#
# Function  : init script, telnetd_startup
#
# Creater   : xiangda.zhang@feixun.com.cn, 2016-05-04
#
# Copyright : Shanghai Phicomm
#
######################################################################

start() {
  /usr/sbin/gpio.sh yellow 0
  sleep 40
  /usr/sbin/gpio.sh blue 0
}

stop() {
  killall -9 led_status
}
start
